/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Task5IndexRouteImport } from './routes/task-5/index'
import { Route as Task15IndexRouteImport } from './routes/task-15/index'
import { Route as Task1IndexRouteImport } from './routes/task-1/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Task5IndexRoute = Task5IndexRouteImport.update({
  id: '/task-5/',
  path: '/task-5/',
  getParentRoute: () => rootRouteImport,
} as any)
const Task15IndexRoute = Task15IndexRouteImport.update({
  id: '/task-15/',
  path: '/task-15/',
  getParentRoute: () => rootRouteImport,
} as any)
const Task1IndexRoute = Task1IndexRouteImport.update({
  id: '/task-1/',
  path: '/task-1/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/task-1': typeof Task1IndexRoute
  '/task-15': typeof Task15IndexRoute
  '/task-5': typeof Task5IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/task-1': typeof Task1IndexRoute
  '/task-15': typeof Task15IndexRoute
  '/task-5': typeof Task5IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/task-1/': typeof Task1IndexRoute
  '/task-15/': typeof Task15IndexRoute
  '/task-5/': typeof Task5IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/task-1' | '/task-15' | '/task-5'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/task-1' | '/task-15' | '/task-5'
  id: '__root__' | '/' | '/task-1/' | '/task-15/' | '/task-5/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Task1IndexRoute: typeof Task1IndexRoute
  Task15IndexRoute: typeof Task15IndexRoute
  Task5IndexRoute: typeof Task5IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-5/': {
      id: '/task-5/'
      path: '/task-5'
      fullPath: '/task-5'
      preLoaderRoute: typeof Task5IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-15/': {
      id: '/task-15/'
      path: '/task-15'
      fullPath: '/task-15'
      preLoaderRoute: typeof Task15IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-1/': {
      id: '/task-1/'
      path: '/task-1'
      fullPath: '/task-1'
      preLoaderRoute: typeof Task1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Task1IndexRoute: Task1IndexRoute,
  Task15IndexRoute: Task15IndexRoute,
  Task5IndexRoute: Task5IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
